from core.server.translate import register_translation

_TRANSLATIONS = {
    "gallery.title": {"en": "Component Demo", "zh_cn": "组件展示"},
    "gallery.subtitle": {"en": "Interactive showcase of all shared components and templates.", "zh_cn": "所有共享组件与模板的交互式展示。"},
    "gallery.theme": {"en": "Theme", "zh_cn": "主题"},
    "gallery.light": {"en": "Light", "zh_cn": "浅色"},
    "gallery.dark": {"en": "Dark", "zh_cn": "深色"},
    "gallery.category_layout": {"en": "Layout", "zh_cn": "布局"},
    "gallery.category_navigation": {"en": "Navigation", "zh_cn": "导航"},
    "gallery.category_data_display": {"en": "Data Display", "zh_cn": "数据展示"},
    "gallery.category_forms": {"en": "Forms", "zh_cn": "表单"},
    "gallery.category_feedback": {"en": "Feedback", "zh_cn": "反馈"},
    "gallery.category_media": {"en": "Media", "zh_cn": "媒体"},
    "gallery.category_ai": {"en": "AI", "zh_cn": "AI"},
    "gallery.category_advanced": {"en": "Advanced", "zh_cn": "高级"},
    "gallery.category_commerce": {"en": "Commerce", "zh_cn": "电商"},
    "gallery.category_templates": {"en": "Templates", "zh_cn": "页面模板"},
    "gallery.control_variant": {"en": "Variant", "zh_cn": "变体"},
    "gallery.control_type": {"en": "Type", "zh_cn": "类型"},
    "gallery.control_size": {"en": "Size", "zh_cn": "尺寸"},
    "gallery.control_direction": {"en": "Direction", "zh_cn": "方向"},
    "gallery.trigger_toast": {"en": "Trigger Toast", "zh_cn": "触发 Toast"},
    "gallery.open_modal": {"en": "Open Modal", "zh_cn": "打开 Modal"},
    "gallery.open_drawer": {"en": "Open Drawer", "zh_cn": "打开 Drawer"},
    "gallery.show_confirm": {"en": "Show Confirm", "zh_cn": "显示 Confirm"},
    "gallery.preview_template": {"en": "Preview Template", "zh_cn": "预览模板"},
    "gallery.close_preview": {"en": "Close Preview", "zh_cn": "关闭预览"},
    "gallery.card_title": {"en": "Card Title", "zh_cn": "卡片标题"},
    "gallery.card_body": {"en": "This is the card body content. Cards support header, media, body and footer slots.", "zh_cn": "这是卡片主体内容。卡片支持 header、media、body 和 footer 插槽。"},
    "gallery.card_footer": {"en": "Card Footer", "zh_cn": "卡片页脚"},
    "gallery.accordion_1": {"en": "What is this platform?", "zh_cn": "这个平台是什么？"},
    "gallery.accordion_1_content": {"en": "An all-in-one framework for building modern web applications with reusable components.", "zh_cn": "一个用于构建现代 Web 应用的一体化框架，提供可复用组件。"},
    "gallery.accordion_2": {"en": "How do I get started?", "zh_cn": "如何开始使用？"},
    "gallery.accordion_2_content": {"en": "Import the shared components and start building. Check the documentation for details.", "zh_cn": "导入共享组件即可开始构建。详情请查看文档。"},
    "gallery.accordion_3": {"en": "Is it open source?", "zh_cn": "它是开源的吗？"},
    "gallery.accordion_3_content": {"en": "Yes, the core framework and all shared components are open source.", "zh_cn": "是的，核心框架和所有共享组件都是开源的。"},
    "gallery.empty_title": {"en": "No Data", "zh_cn": "暂无数据"},
    "gallery.empty_desc": {"en": "There is nothing to display here yet.", "zh_cn": "这里还没有内容可显示。"},
    "gallery.step_1": {"en": "Cart", "zh_cn": "购物车"},
    "gallery.step_2": {"en": "Shipping", "zh_cn": "配送"},
    "gallery.step_3": {"en": "Payment", "zh_cn": "支付"},
    "gallery.step_4": {"en": "Confirm", "zh_cn": "确认"},
    "gallery.timeline_1": {"en": "Order placed", "zh_cn": "订单已下单"},
    "gallery.timeline_2": {"en": "Processing", "zh_cn": "处理中"},
    "gallery.timeline_3": {"en": "Shipped", "zh_cn": "已发货"},
    "gallery.timeline_4": {"en": "Delivered", "zh_cn": "已送达"},
    "gallery.modal_title": {"en": "Modal Example", "zh_cn": "Modal 示例"},
    "gallery.modal_body": {"en": "This is a modal dialog. You can change its size, disable mask click, and more.", "zh_cn": "这是一个模态对话框。你可以更改尺寸、禁用遮罩点击等。"},
    "gallery.drawer_title": {"en": "Drawer Example", "zh_cn": "Drawer 示例"},
    "gallery.drawer_body": {"en": "Drawers slide in from any edge. This one is on the right.", "zh_cn": "抽屉可以从任意边缘滑入。这个在右侧。"},
    "gallery.confirm_title": {"en": "Are you sure?", "zh_cn": "确定吗？"},
    "gallery.confirm_msg": {"en": "This action cannot be undone.", "zh_cn": "此操作无法撤销。"},
    "gallery.tree_data": {"en": "Project Files", "zh_cn": "项目文件"},
    "gallery.search_placeholder": {"en": "Search components...", "zh_cn": "搜索组件..."},
    "gallery.carousel_slide_1": {"en": "Slide 1", "zh_cn": "幻灯片 1"},
    "gallery.carousel_slide_2": {"en": "Slide 2", "zh_cn": "幻灯片 2"},
    "gallery.carousel_slide_3": {"en": "Slide 3", "zh_cn": "幻灯片 3"},
    "gallery.template_frontpage": {"en": "Frontpage", "zh_cn": "首页"},
    "gallery.template_dashboard": {"en": "Dashboard", "zh_cn": "仪表盘"},
    "gallery.template_landing": {"en": "Landing", "zh_cn": "落地页"},
    "gallery.template_profile": {"en": "Profile", "zh_cn": "个人主页"},
    "gallery.template_chat": {"en": "Chat", "zh_cn": "聊天"},
    "gallery.template_ecommerce": {"en": "E-commerce", "zh_cn": "电商"},
    "gallery.template_magazine": {"en": "Magazine", "zh_cn": "杂志"},
    "gallery.template_tutorial": {"en": "Tutorial", "zh_cn": "教程"},
    "gallery.template_video": {"en": "Video", "zh_cn": "视频"},
    "gallery.template_form": {"en": "Form", "zh_cn": "表单"},
    "gallery.ai_placeholder": {"en": "Ask me anything...", "zh_cn": "问我任何问题..."},
    "gallery.ai_send": {"en": "Send", "zh_cn": "发送"},
    "gallery.code_example": {"en": "Code Example", "zh_cn": "代码示例"},
    "gallery.suggestion_1": {"en": "Explain components", "zh_cn": "解释组件"},
    "gallery.suggestion_2": {"en": "Show templates", "zh_cn": "展示模板"},
    "gallery.suggestion_3": {"en": "Dark mode tips", "zh_cn": "深色模式技巧"},
}

for key, langs in _TRANSLATIONS.items():
    for lang, text in langs.items():
        register_translation(key, lang, text)
