from core.server.translate import register_translation

_TRANSLATIONS = {
    "eshop.title": {"en": "e-Shop", "zh_cn": "e-Shop"},
    "eshop.ai_customer_service": {"en": "AI Customer Service", "zh_cn": "AI 客服"},
    "eshop.my_orders": {"en": "My Orders", "zh_cn": "我的订单"},
    "eshop.cart": {"en": "Cart", "zh_cn": "购物车"},
    "eshop.user_profile": {"en": "Profile", "zh_cn": "个人中心"},
    "eshop.logout": {"en": "Logout", "zh_cn": "退出"},
    "eshop.loading": {"en": "Loading...", "zh_cn": "加载中..."},
    "eshop.back_to_mall": {"en": "Back to Mall", "zh_cn": "返回商城"},
    "eshop.view_details": {"en": "View Details", "zh_cn": "查看详情"},
    "eshop.add_to_cart": {"en": "Add to Cart", "zh_cn": "加入购物车"},
    "eshop.product_detail": {"en": "Product Detail", "zh_cn": "商品详情"},
    "eshop.user_reviews": {"en": "User Reviews", "zh_cn": "用户评价"},
    "eshop.no_reviews": {"en": "No Reviews", "zh_cn": "暂无评价"},
    "eshop.product_not_found": {"en": "Product Not Found", "zh_cn": "商品不存在"},
    "eshop.cart_empty": {"en": "Cart is Empty", "zh_cn": "购物车是空的"},
    "eshop.go_to_checkout": {"en": "Checkout", "zh_cn": "去结算"},
    "eshop.delete": {"en": "Delete", "zh_cn": "删除"},
    "eshop.checkout": {"en": "Checkout", "zh_cn": "结算"},
    "eshop.back_to_cart": {"en": "Back to Cart", "zh_cn": "返回购物车"},
    "eshop.shipping_info": {"en": "Shipping Info", "zh_cn": "收货信息"},
    "eshop.name_placeholder": {"en": "Recipient Name", "zh_cn": "收货人姓名"},
    "eshop.phone_placeholder": {"en": "Phone", "zh_cn": "联系电话"},
    "eshop.address_placeholder": {"en": "Address", "zh_cn": "详细地址"},
    "eshop.order_summary": {"en": "Order Summary", "zh_cn": "订单摘要"},
    "eshop.submit_order": {"en": "Submit Order", "zh_cn": "提交订单"},
    "eshop.order_success": {"en": "Order submitted! ID: ", "zh_cn": "订单提交成功！订单号: "},
    "eshop.submit_failed": {"en": "Submit Failed", "zh_cn": "提交失败"},
    "eshop.login": {"en": "Login", "zh_cn": "登录"},
    "eshop.username_placeholder": {"en": "Username", "zh_cn": "用户名"},
    "eshop.password_placeholder": {"en": "Password", "zh_cn": "密码"},
    "eshop.login_failed": {"en": "Invalid username or password", "zh_cn": "用户名或密码错误"},
    "eshop.test_account": {"en": "Test account", "zh_cn": "测试账号"},
    "eshop.order_id": {"en": "Order ID", "zh_cn": "订单号"},
    "eshop.status": {"en": "Status", "zh_cn": "状态"},
    "eshop.created_at": {"en": "Created At", "zh_cn": "创建时间"},
    "eshop.user_id": {"en": "User ID", "zh_cn": "用户ID"},
    "eshop.product_list": {"en": "Product List", "zh_cn": "商品列表"},
    "eshop.total": {"en": "Total", "zh_cn": "合计"},
    "eshop.order_not_found": {"en": "Order Not Found", "zh_cn": "订单不存在"},
    "eshop.missing_order_id": {"en": "Missing Order ID", "zh_cn": "缺少订单号"},
    "eshop.back_to_orders": {"en": "Back to Orders", "zh_cn": "返回订单列表"},
    "eshop.user_info": {"en": "User Info", "zh_cn": "用户信息"},
    "eshop.name": {"en": "Name", "zh_cn": "姓名"},
    "eshop.phone": {"en": "Phone", "zh_cn": "电话"},
    "eshop.email": {"en": "Email", "zh_cn": "邮箱"},
    "eshop.address": {"en": "Address", "zh_cn": "地址"},
    "eshop.order_history": {"en": "Order History", "zh_cn": "订单历史"},
    "eshop.no_orders": {"en": "No Orders", "zh_cn": "暂无订单"},
    "eshop.ai_greeting": {"en": "Hello! How can I help you?", "zh_cn": "您好！有什么可以帮您的吗？"},
    "eshop.ai_greeting_full": {"en": "Hello! I'm e-Shop AI assistant. I can help with products, pricing, shipping, and after-sales.", "zh_cn": "您好！我是 e-Shop 的 AI 客服，可以帮您解答商品、价格、发货、售后等问题。"},
    "eshop.input_question": {"en": "Type a question...", "zh_cn": "输入问题..."},
    "eshop.send": {"en": "Send", "zh_cn": "发送"},
    "eshop.cart_drawer_label": {"en": "Shopping Cart", "zh_cn": "购物车"},
    "eshop.checkout_success": {"en": "Checkout Successful!", "zh_cn": "结算成功！"},
    "eshop.added_to_cart": {"en": "Added to Cart", "zh_cn": "已加入购物车"},
    "eshop.theme_light": {"en": "Light", "zh_cn": "浅色"},
    "eshop.theme_dark": {"en": "Dark", "zh_cn": "深色"},
    "eshop.search": {"en": "Search", "zh_cn": "搜索"},
    "eshop.search_placeholder": {"en": "Search products...", "zh_cn": "搜索商品..."},
    "eshop.no_results": {"en": "No products found", "zh_cn": "未找到商品"},
    "eshop.welcome": {"en": "Welcome", "zh_cn": "欢迎"},
    "eshop.register": {"en": "Register", "zh_cn": "注册"},
    "eshop.confirm_password": {"en": "Confirm Password", "zh_cn": "确认密码"},
    "eshop.password_mismatch": {"en": "Passwords do not match", "zh_cn": "密码不一致"},
    "eshop.register_success": {"en": "Registration successful", "zh_cn": "注册成功"},
    "eshop.ai_typing": {"en": "AI is typing...", "zh_cn": "AI 正在输入..."},
    "eshop.service_unavailable": {"en": "Service temporarily unavailable", "zh_cn": "服务暂时不可用"},
    "eshop.network_error": {"en": "Network error, please try again later.", "zh_cn": "网络错误，请稍后再试。"},
    "eshop.favorites": {"en": "Favorites", "zh_cn": "我的收藏"},
    "eshop.no_favorites": {"en": "No favorites yet", "zh_cn": "暂无收藏"},
    "eshop.categories": {"en": "Categories", "zh_cn": "分类"},
    "eshop.recommendations": {"en": "Recommended", "zh_cn": "为你推荐"},
    "eshop.stock": {"en": "Stock", "zh_cn": "库存"},
    "eshop.sales": {"en": "Sales", "zh_cn": "销量"},
    "eshop.coupons": {"en": "Coupons", "zh_cn": "优惠券"},
    "eshop.apply_coupon": {"en": "Apply Coupon", "zh_cn": "使用优惠券"},
    "eshop.coupon_applied": {"en": "Coupon applied", "zh_cn": "优惠券已使用"},
    "eshop.write_review": {"en": "Write a review", "zh_cn": "写评价"},
    "eshop.submit_review": {"en": "Submit Review", "zh_cn": "提交评价"},
    "eshop.rating": {"en": "Rating", "zh_cn": "评分"},
    "eshop.review_placeholder": {"en": "Share your experience...", "zh_cn": "分享您的使用体验..."},
    "eshop.order_detail": {"en": "Order Detail", "zh_cn": "订单详情"},
    "eshop.order_info": {"en": "Order Info", "zh_cn": "订单信息"},
    "eshop.order_tracking": {"en": "Order Tracking", "zh_cn": "订单跟踪"},
    "eshop.order_created": {"en": "Order Created", "zh_cn": "订单创建"},
    "eshop.order_confirmed": {"en": "Confirmed", "zh_cn": "订单确认"},
    "eshop.order_confirmed_desc": {"en": "Seller confirmed", "zh_cn": "商家已确认订单"},
    "eshop.order_shipped": {"en": "Shipped", "zh_cn": "已发货"},
    "eshop.order_shipped_desc": {"en": "Item shipped", "zh_cn": "商品已发出"},
    "eshop.order_delivered": {"en": "Delivered", "zh_cn": "已送达"},
    "eshop.order_delivered_desc": {"en": "Order completed", "zh_cn": "订单已完成"},
    "eshop.order_submitted": {"en": "Order submitted", "zh_cn": "订单已提交"},
    "eshop.buy_now": {"en": "Buy Now", "zh_cn": "立即购买"},
    "eshop.description": {"en": "Description", "zh_cn": "商品描述"},
    "eshop.specs": {"en": "Specifications", "zh_cn": "规格参数"},
    "eshop.no_description": {"en": "No description", "zh_cn": "暂无描述"},
    "eshop.size": {"en": "Size", "zh_cn": "尺寸"},
    "eshop.related_products": {"en": "Related Products", "zh_cn": "相关推荐"},
    "eshop.no_image": {"en": "No image", "zh_cn": "暂无图片"},
    "eshop.first_name": {"en": "First Name", "zh_cn": "名"},
    "eshop.last_name": {"en": "Last Name", "zh_cn": "姓"},
    "eshop.city": {"en": "City", "zh_cn": "城市"},
    "eshop.postal_code": {"en": "Postal Code", "zh_cn": "邮编"},
    "eshop.country": {"en": "Country", "zh_cn": "国家"},
    "eshop.payment_method": {"en": "Payment Method", "zh_cn": "支付方式"},
    "eshop.card": {"en": "Card", "zh_cn": "银行卡"},
    "eshop.paypal": {"en": "PayPal", "zh_cn": "PayPal"},
    "eshop.cod": {"en": "Cash on Delivery", "zh_cn": "货到付款"},
    "eshop.discount_code": {"en": "Discount code", "zh_cn": "优惠码"},
    "eshop.apply": {"en": "Apply", "zh_cn": "应用"},
    "eshop.subtotal": {"en": "Subtotal", "zh_cn": "小计"},
    "eshop.shipping": {"en": "Shipping", "zh_cn": "运费"},
    "eshop.discount": {"en": "Discount", "zh_cn": "优惠"},
    "eshop.place_order": {"en": "Place Order", "zh_cn": "提交订单"},
    "eshop.favorite_added": {"en": "Added to favorites", "zh_cn": "已加入收藏"},
    "eshop.favorite_removed": {"en": "Removed from favorites", "zh_cn": "已取消收藏"},
    # Merchant / Role
    "eshop.merchant_console": {"en": "Merchant Console", "zh_cn": "商家后台"},
    "eshop.merchant_headline": {"en": "Manage your store.", "zh_cn": "管理你的店铺。"},
    "eshop.merchant_lead": {"en": "Products, orders, coupons and analytics are in separate pages.", "zh_cn": "商品、订单、优惠券和数据统计分布在独立页面。"},
    "eshop.customer": {"en": "Customer", "zh_cn": "顾客端"},
    "eshop.merchant": {"en": "Merchant", "zh_cn": "商家端"},
    "eshop.admin": {"en": "Admin", "zh_cn": "管理员"},
    "eshop.role": {"en": "Role", "zh_cn": "角色"},
    "eshop.test_accounts": {"en": "Test accounts", "zh_cn": "测试账户"},
    "eshop.fill_required": {"en": "Please fill in required fields", "zh_cn": "请填写必要字段"},
    "eshop.merchant_products": {"en": "Product Management", "zh_cn": "商品管理"},
    "eshop.merchant_orders": {"en": "Order Management", "zh_cn": "订单管理"},
    "eshop.merchant_coupons": {"en": "Coupon Management", "zh_cn": "优惠券管理"},
    "eshop.merchant_products_desc": {"en": "Add, edit and manage product inventory.", "zh_cn": "添加、编辑和管理商品库存。"},
    "eshop.merchant_orders_desc": {"en": "Review and process all customer orders.", "zh_cn": "查看和处理所有顾客订单。"},
    "eshop.merchant_coupons_desc": {"en": "Create and issue store coupons.", "zh_cn": "创建和发放店铺优惠券。"},
    "eshop.merchant_back_home_desc": {"en": "Return to the customer storefront.", "zh_cn": "回到顾客端商城首页。"},
    "eshop.merchant_stats": {"en": "Statistics", "zh_cn": "数据统计"},
    "eshop.product_name": {"en": "Product Name", "zh_cn": "商品名称"},
    "eshop.price": {"en": "Price", "zh_cn": "价格"},
    "eshop.category": {"en": "Category", "zh_cn": "分类"},
    "eshop.actions": {"en": "Actions", "zh_cn": "操作"},
    "eshop.add_product": {"en": "Add Product", "zh_cn": "添加商品"},
    "eshop.edit": {"en": "Edit", "zh_cn": "编辑"},
    "eshop.save": {"en": "Save", "zh_cn": "保存"},
    "eshop.cancel": {"en": "Cancel", "zh_cn": "取消"},
    "eshop.all_orders": {"en": "All Orders", "zh_cn": "全部订单"},
    "eshop.revenue": {"en": "Revenue", "zh_cn": "收入"},
    "eshop.product_count": {"en": "Products", "zh_cn": "商品数"},
    "eshop.order_count": {"en": "Orders", "zh_cn": "订单数"},
    "eshop.enter_merchant": {"en": "Merchant Console", "zh_cn": "进入商家后台"},
    "eshop.back_to_home": {"en": "Back to Home", "zh_cn": "返回首页"},
    "eshop.back_to_console": {"en": "Back to Console", "zh_cn": "返回商家后台"},
    "eshop.add_coupon": {"en": "Add Coupon", "zh_cn": "添加优惠券"},
    "eshop.edit_product": {"en": "Add / Edit Product", "zh_cn": "添加/编辑商品"},
    "eshop.coupon_list": {"en": "Coupon List", "zh_cn": "优惠券列表"},
    "eshop.no_products": {"en": "No products", "zh_cn": "暂无商品"},
    "eshop.no_coupons": {"en": "No coupons", "zh_cn": "暂无优惠券"},
    "eshop.confirm_delete": {"en": "Delete this item?", "zh_cn": "确认删除？"},
    "eshop.fill_code": {"en": "Please enter coupon code", "zh_cn": "请填写优惠码"},
    "eshop.product_id_placeholder": {"en": "Product ID", "zh_cn": "商品ID"},
    "eshop.original_price": {"en": "Original Price", "zh_cn": "原价"},
    "eshop.image_url": {"en": "Image URL", "zh_cn": "图片URL"},
    "eshop.tags_hint": {"en": "Tags (comma separated)", "zh_cn": "标签(逗号分隔)"},
    "eshop.coupon_id_placeholder": {"en": "Coupon ID", "zh_cn": "优惠券ID"},
    "eshop.coupon_code_placeholder": {"en": "Coupon Code", "zh_cn": "优惠码"},
    "eshop.discount_amount": {"en": "Discount Amount", "zh_cn": "优惠金额"},
    "eshop.min_order": {"en": "Min Order", "zh_cn": "最低订单金额"},
    "eshop.coupon_summary": {"en": "Min ¥{min} off ¥{discount} · {desc}", "zh_cn": "满¥{min}减¥{discount} · {desc}"},
    "eshop.status_pending": {"en": "Pending", "zh_cn": "待付款"},
    "eshop.status_paid": {"en": "Paid", "zh_cn": "已付款"},
    "eshop.status_shipped": {"en": "Shipped", "zh_cn": "已发货"},
    "eshop.status_delivered": {"en": "Delivered", "zh_cn": "已送达"},
    "eshop.status_cancelled": {"en": "Cancelled", "zh_cn": "已取消"},
    "eshop.no_merchant_orders": {"en": "No orders yet", "zh_cn": "暂无订单"},
    "eshop.err_username_exists": {"en": "Username already taken", "zh_cn": "用户名已被注册"},
    "eshop.err_invalid_credentials": {"en": "Invalid username or password", "zh_cn": "用户名或密码错误"},
    "eshop.err_invalid_action": {"en": "Invalid action", "zh_cn": "请求动作无效"},
    "eshop.err_not_logged_in": {"en": "Not logged in", "zh_cn": "请先登录"},
}

for key, langs in _TRANSLATIONS.items():
    for lang, text in langs.items():
        register_translation(key, lang, text)
